// <auto-generated />
using HotelListing5._0.Controllers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelListing5._0.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220222061246_SeedingData")]
    partial class SeedingData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HotelListing5._0.Controllers.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shortname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jamaica",
                            Shortname = "JM"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bahamas",
                            Shortname = "BS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cayman Island",
                            Shortname = "CI"
                        });
                });

            modelBuilder.Entity("HotelListing5._0.Controllers.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountrId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Ranting")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountrId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Negril",
                            CountrId = 1,
                            Name = "Sandals Resort and Spa",
                            Ranting = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "George Town",
                            CountrId = 3,
                            Name = "Comfort Suites",
                            Ranting = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Nassua",
                            CountrId = 2,
                            Name = "Grand Palldium",
                            Ranting = 4.0
                        });
                });

            modelBuilder.Entity("HotelListing5._0.Controllers.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing5._0.Controllers.Data.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
